torchrun --nproc_per_node=4 fastchat/train/train_mem.py \
    --model_name_or_path pinkmanlove/llama-33b-hf \
    --data_path data/Reflection_Wiz_All_QA.json \
    --cache_dir ../cache \
    --bf16 True \
    --output_dir trained_models/Reflection_Wiz_All_QA_33B \
    --num_train_epochs 3 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 32 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 2000 \
    --save_total_limit 1 \
    --learning_rate 2e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --fsdp "full_shard auto_wrap offload" \
    --fsdp_transformer_layer_cls_to_wrap 'LlamaDecoderLayer' \
    --tf32 True \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --lazy_preprocess True

